// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2aETBddeDhxHrYQaB0IzdURMXKb8iS8g',
    appId: '1:792184544044:android:9b07297223c2cad9a42a89',
    messagingSenderId: '792184544044',
    projectId: 'flutter-ui-84e30',
    storageBucket: 'flutter-ui-84e30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu-T-CyTVayRbfYS8qzq63Seu4u7677rY',
    appId: '1:792184544044:ios:7f21bcab38ac6466a42a89',
    messagingSenderId: '792184544044',
    projectId: 'flutter-ui-84e30',
    storageBucket: 'flutter-ui-84e30.appspot.com',
    androidClientId: '792184544044-lnq49jrl6mh6k20e9r42p8nu2np133ml.apps.googleusercontent.com',
    iosClientId: '792184544044-ogvq40ifkauugr7vi4e5v6ntdnbj7ocp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUiApp',
  );
}
